name: env_int2vec
dependencies:
  - python>3.6.1
  # Analysis
  - matplotlib
  - seaborn
  # Calculations
  - nomkl
  - numpy
  - scikit-learn
  - scipy
  # Reporting
  - pandas
  # Packages
  - pip
  - pip:
    - tensorflow
    - git+https://github.com/zsdonghao/tensorlayer.git
